repos:
  - repo: git://github.com/dnephin/pre-commit-golang
    rev: v0.4.0
    hooks:
      - id: go-fmt
      - id: go-imports
      - id: go-unit-tests
      - id: no-go-testing
      - id: golangci-lint
      - id: go-build
      - id: go-mod-tidy